description = "A Europass-compliant CV"

# Top-level theme parameters
sidebarWidth = "wide"
columnGap = "small"
showEuropassBranding = true
useEuropassDateFormat = true
defaultTheme = "default"  # Default theme to use (must match an id in colorschemes.yaml)

# All formatting-related settings consolidated
[formatting]
  # Typography settings
  [formatting.typography]
    useSystemFonts = false  # Set to true to use system fonts instead of web fonts
    headingFont = "Roboto Slab"
    bodyFont = "Roboto"
  
  # Font sizes
  [formatting.sizes]
    heading = "1.5rem"
    body = "1rem"
    small = "0.875rem"
    sidebarHeading = "1.25rem"
  
  # Spacing configuration
  [formatting.spacing]
    sectionMargin = "2.5rem"
    itemMargin = "0.5rem"
  
  # Name and title formatting (new in Phase 6)
  [formatting.name]
    firstName_size = "text-4xl"
    firstName_color = "text-primary-700 dark:text-primary-300"
    firstName_font = "font-semibold"
    lastName_size = "text-4xl"
    lastName_color = "text-neutral-800 dark:text-neutral-200" 
    lastName_font = "font-bold"
  
  [formatting.job]
    title_size = "text-xl"
    title_color = "text-secondary-700 dark:text-secondary-300"
    title_font = "font-medium"

# Configure layout sections (sections are rendered in the order listed)
[layout]
sidebar = [
  "personal_details",
  "online_profiles",
  "driving_licence",
  "language_skills",
  "hobbies_interests",
  "management_leadership_skills",
]
main = [
  "summary",
  "work_experience",
  "education",
  "publications",
  "conferences_seminars",
  "projects",
  "honours_awards",
  "digital_skills",
  "communication_interpersonal_skills",
]